### ISSUE TITLE
Message deleted by the author may not be true always

### ISSUE THREAD

**Issue by AmeyWale** [StockerMC/discord.py#1]
### Summary

When on message delete event is received, the user who deleted the message may not be the author

### Reproduction Steps

Delete a discord message

### Expected Results

The user who deleted the message can be fetched from the audit logs

### Actual Results

The user who deleted the message can be fetched from the audit logs

### Intents

discord.Intents.all()

### System Information

I did not installed this lib yet

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I raised this issue from the code that was written in examples folder

**Comment by StockerMC** [comment]
Thanks for the suggestion. The wording in the example has been changed.
